[package]
name = "yaavre"
version = "0.1.0"
authors = ["Y. Sapir <yasapir@gmail.com>"]

[dependencies]
hex = "0.3.1"
clap = "2.31"
signal-notify = "0.1.3"
disa = { git = "git://github.com/sapir/disa" }
byteorder = "1.2.3"
